# Site settings
title: mrprompt
email: mrprompt@gmail.com
description: blog do desenvolvedor web Thiago Paes - mrprompt

# Build settings
name: Thiago mrprompt Paes - Blog Pessoal
markdown: redcarpet
highlighter: pygments
timezone: America/Sao_Paulo
permalink: pretty