# Site settings
title: Thiago Paes - Blog Pessoal
email: mrprompt@gmail.com
url: https://mrprompt.com.br
description: Blog pessoal do desenvolvedor web Thiago Paes - mrprompt

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: https://mrprompt.com.br

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/mrprompt

# Build settings
markdown: kramdown
permalink: pretty
