theme: minima

# Site settings
title: mrprompt
email: mrprompt@gmail.com
url: "/blog"
description: Este é meu site pessoal e nele você pode me conhecer e alguns dos meus projetos.

# Build settings
markdown: kramdown
permalink: pretty

minima:
  skin: classic