# Site settings
title: Thiago Paes - Blog Pessoal
description: Blog pessoal do desenvolvedor web Thiago Paes - mrprompt

# Build settings
name: Thiago Paes - Blog Pessoal
markdown: redcarpet
highlighter: pygments
timezone: America/Sao_Paulo
permalink: pretty
url: http://www.mrprompt.com.br
paginate: 3
pagination_path: "/:num"
