remote_theme: "jekyll/minima@1e8a445"

# Site settings
title: mrprompt
email: mrprompt@gmail.com
url: "/blog"
description: Um punhado de testados de escrevi para meu antigo blog.

# Build settings
markdown: kramdown
permalink: pretty

minima:
  skin: classic
