# Site settings
title: Thiago Paes - Blog Pessoal
description: Blog pessoal do desenvolvedor web Thiago Paes - mrprompt
url: https://www.mrprompt.com.br
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
highlighter: rouge
timezone: America/Sao_Paulo
permalink: pretty

# Pagination
paginate: 3
pagination_path: "/:num"

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: compressed
