# Site settings
title: Thiago Paes - Blog Pessoal
description: Blog pessoal do desenvolvedor web Thiago Paes - mrprompt
url: https://www.mrprompt.com.br
baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
highlighter: rouge
timezone: America/Sao_Paulo
permalink: pretty

# Pagination
paginate: 5
pagination_path: "/:num"

# Use your search engine ID
google_cse_id: "002596954644940765615:oyvb7cllqbi" 

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-google_cse

sass:
  style: compressed
