# Site settings
title: mrprompt
email: mrprompt@gmail.com
description: mrprompt.com.br desenvolvimento web
baseurl: ""
url: "http://mrprompt.com.br"
github_username: mrprompt

# Build settings
name: Thiago mrprompt Paes - Site Pessoal
markdown: redcarpet
highlighter: pygments
timezone: America/Sao_Paulo
limit_posts: 0
paginate: 5
paginate_path: page:num
permalink: pretty