remote_theme: "jekyll/minima@1e8a445"

# Site settings
title: mrprompt
email: contato@mrprompt.com.br
url: "/blog"
description: Um punhado de textos que escrevi para meu antigo blog.

# Build settings
markdown: kramdown
permalink: pretty
lang: pt-br

minima:
  skin: classic
  date_format: "%d-%m-%Y"
  hide_site_feed_link: false
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/mrprompt"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/paesthiago/"
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/onegaothiago/"
    
author:
  name: mrprompt
  email: contato@mrprompt.com.br
